### ISSUE TITLE
【ModuleNotFoundError: No module named 'outputs'】

### ISSUE THREAD

**Issue by guxinyu1225** [TAP-LLM/SplitFedLLM#1]
运行python ./FedGLM/flserver.py后显示File "/home/ma-user/work/SplitFedLLM/FedGLM/server/server_model.py", line 29, in <module>
    from outputs import SplitModelPartAOutput 
ModuleNotFoundError: No module named 'outputs'
请问outputs文件在哪？

**Comment by Jane-Zheng** [comment]
我们已经上传了outputs.py文件，并解决了一些已发现的bug，我们将会继续更新程序，感谢您的关注。
